spring:
  profiles:
    active: "devH2"


---

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost/diploma?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: none

    properties:
      org:
        hibernate:
          envers:
            audit_table_prefix: audit_


#logging:
#  level: warn

---
name: devH2
spring:
  jpa:
    hibernate:
      ddl-auto: create
    #      ddl-auto: none

    properties:
      org:
        hibernate:
          envers:
            audit_table_prefix: audit_

jwt:
  signing:
    key: secret
  token:
    validity: 1800000 # 100 * 60 * 60 * 5
  authorities:
    key: roles
